/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_or_aesop_HelloWorld */

#ifndef _Included_kr_or_aesop_HelloWorld
#define _Included_kr_or_aesop_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_or_aesop_HelloWorld
 * Method:    show1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_or_aesop_HelloWorld_show1
  (JNIEnv *, jobject);

/*
 * Class:     kr_or_aesop_HelloWorld
 * Method:    show2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_kr_or_aesop_HelloWorld_show2
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_or_aesop_HelloWorld
 * Method:    show3
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_kr_or_aesop_HelloWorld_show3
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     kr_or_aesop_HelloWorld
 * Method:    show4
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_kr_or_aesop_HelloWorld_show4
  (JNIEnv *, jobject, jchar);

/*
 * Class:     kr_or_aesop_HelloWorld
 * Method:    show5
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_kr_or_aesop_HelloWorld_show5
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     kr_or_aesop_HelloWorld
 * Method:    show6
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_kr_or_aesop_HelloWorld_show6__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     kr_or_aesop_HelloWorld
 * Method:    show6
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_or_aesop_HelloWorld_show6__
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
